#!/bin/bash

set -e

VERSION=v4.1.4

help() {
  echo "Usage:"
  echo "  zmicro package install gotop <args...>"
  echo ""
}

install() {
  local arch="$(os::arch)"
  local os="linux"
  local bin_path=/usr/bin

  if [ "$(os::is_macos)" = "true" ]; then
    os="darwin"
    bin_path=/usr/local/bin
  fi

  local tmp_file=/tmp/gotop.tar.gz

  local url="https://github.com/xxxserxxx/gotop/releases/download/${VERSION}/gotop_${VERSION}_${os}_${arch}.tgz"
  curl -fSL $url -o $tmp_file

  cd /tmp
  tar -zxvf $tmp_file >>/dev/null 2>&1

  sudo mv gotop $bin_path

  rm -rf $tmp_file
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  log::success "install gotop success."
}

run() {
  core $@
}

run $@
